### PR TITLE
Fix BC date off-by-one bug

### LINKED ISSUE #5: BC dates are parsed incorrectly
ISO 8601, since the 2000 version, uses astronomical year numbering, meaning that 1 BC is represented as "year 0" in timestamps, 2 BC as -1, and so on. JS date objects follow this format, as explicitly noted in ES spec here: https://tc39.github.io/ecma262/#sec-expanded-years

> Examples of date-time values with expanded years:
>
> -271821-04-20T00:00:00Z | 271822 B.C.
> -000001-01-01T00:00:00Z | 2 B.C.
> +000000-01-01T00:00:00Z | 1 B.C.
> +000001-01-01T00:00:00Z | 1 A.D.

Postgres, on the other hand, considers "year 0" invalid, and BC years are represented as they are, just with a `BC` suffix appended at the end of the timestamp.

This means that there's a mismatch and parsed `Date` objects are a year out. You can prove it by looking at the Unix timestamps:

```
=# SELECT timestamptz '0001-01-01T00:00:00Z BC', EXTRACT(EPOCH FROM timestamptz '0001-01-01T00:00:00Z BC');

        timestamptz        │  date_part
───────────────────────────┼──────────────
 0001-01-01 00:00:00+00 BC │ -62167219200
```

```js
> var dateObj = parse('0001-01-01 00:00:00+00 BC')
> dateObj.toISOString()
'-000001-01-01T00:00:00.000Z'
> dateObj.getTime() / 1000
-62198755200  // Doesn't match Postgres!

> new Date('0000-01-01T00:00:00Z').getTime() / 1000
-62167219200  // Matches
```

### PR DESCRIPTION
**Pull request by noinkling**
Fixes #5 

Also fixes BC `date` type output, which currently isn't parsing at all. e.g. `1234-01-01 BC`

Related: brianc/node-postgres#1864

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -43,7 +45,7 @@ module.exports = function parseDate (isoDate) {
     date = new Date(year, month, day, hour, minute, second, ms)
   }
 
-  if (isFirstCentury) {
+  if (yearIsBetween0And99) {
```
Comment (bendrucker) [inline index.js]: Would rather remove this var and just move the check here, since it's not reused

File: index.js [hunk 2]
```diff
@@ -52,7 +54,13 @@ module.exports = function parseDate (isoDate) {
 
 function getDate (isoDate) {
   var matches = DATE.exec(isoDate)
+
   var year = parseInt(matches[1], 10)
+  var isBC = !!matches[4]
+  if (isBC) {
```
Comment (bendrucker) [inline index.js]: isBC is calculated elsewhere with a second regex. Fine with using the match from the main one, but please update the other fn to match and remove `BC`.

**Comment by noinkling** [comment]
I updated the BC detection as requested.

Instead of inlining the "0 to 99" check I fixed another edge case due to `setUTCFullYear` being used for local times (as well as timezone qualified ones), when it should be using `setFullYear`. For example, in my current timezone:

```js
> var date1 = new Date("1976-01-01T01:15:30+12:00")
> var date2 = new Date(date1)
> date1.setUTCFullYear(76)
-59737257870000
> date2.setFullYear(76)
-59768875414000
> date1.toISOString()
"0076-12-31T13:15:30.000Z"
> date2.toISOString()
"0075-12-31T14:36:26.000Z"
```

I didn't add a test because it's local timezone dependent and I don't know how to control that (at least without a more elaborate setup).

**Comment by noinkling** [comment]
...And fixed one more bug, with a test case for this one. Hopefully that's all.

**Comment by bendrucker** [comment]
Thanks!
